Add files via upload

diff --git a/run b/run
--- a/run
+++ b/run
@@ -6,7 +6,7 @@
 #      ▇▇            @hrjir     ▇▇▇▇▇▇▇▇▇▇▇▇▇          ▇▇▇▇▇▇▇▇▇▇ 
 #      ▇▇                            ▇▇                         ▇▇          ▇▇                 ▇▇ 
 #      ▇▇                            ▇▇                         ▇▇          ▇▇                 ▇▇ 
-#      ▇▇▄▄▄▄▄▄           ▇▇                         ▇▇          ▇▇▇▇▇▇▇▇▇▇   ¦ Source ALLHB-LHB BY @hrjir
+#      ▇▇▄▄▄▄▄▄           ▇▇                         ▇▇          ▇▇▇▇▇▇▇▇▇▇   ¦ Source LHB BY @hrjir
 #---------------------------------------------------------------------
 cd $(cd $(dirname $0); pwd)
  
@@ -28,11 +28,11 @@ echo -e "${GREEN}
       ▇▇            @hrjir     ▇▇▇▇▇▇▇▇▇▇▇▇▇          ▇▇▇▇▇▇▇▇▇▇ 
       ▇▇                            ▇▇                         ▇▇          ▇▇                 ▇▇ 
       ▇▇                            ▇▇                         ▇▇          ▇▇                 ▇▇ 
-      ▇▇▄▄▄▄▄▄           ▇▇                         ▇▇          ▇▇▇▇▇▇▇▇▇▇   ¦ Source ALLHB-LHB BY @hrjir
+      ▇▇▄▄▄▄▄▄           ▇▇                         ▇▇          ▇▇▇▇▇▇▇▇▇▇   ¦ Source LHB BY @hrjir
 ----------------------------------------------------------------------${CNIL}"
 echo -e "${RED}| للاسف لايمكنك تنصيب السورس ع نظام اوبنتو {${Version}} يجب ان يكون على اصدار  اقل مثلا  ${SMAY}14 او 16
 ${CNIL}";
-echo -e "${RED}| Sorry Canot install Source on Ubuntu {${Version}} Please install system To Ubuntu ${SMAY}14 or 16 ${RED} For Run The Source ALLHB-LHB 
+echo -e "${RED}| Sorry Canot install Source on Ubuntu {${Version}} Please install system To Ubuntu ${SMAY}14 or 16 ${RED} For Run The Source LHB 
 ${CNIL}";
 exit;
 fi
@@ -42,7 +42,7 @@ if [ ! -f "./TG" ]; then
 echo -e "${RED}
 ¦
 ¦ CAUTION:${WHITB} Your Not Dwonload TG .
-¦ NOW I Run File ${Yellow}./run${WHITB} To install ${SMAY}Source ALLHB-LHB${CNIL} . \n
+¦ NOW I Run File ${Yellow}./run${WHITB} To install ${SMAY}Source LHB${CNIL} . \n
 \n\n"
 chmod +x ./ins
 ./ins
@@ -71,9 +71,9 @@ sudo rm -fr ../.telegram-cli
 done
 else
 
-if ! screen -list | grep -q "ALLHB-LHB"; then
-screen -S ALLHB-LHB ./run R
+if ! screen -list | grep -q "LHB"; then
+screen -S LHB ./run R
 fi
-screen -S ALLHB-LHB -X kill
-screen -S ALLHB-LHB ./run R
+screen -S LHB -X kill
+screen -S LHB ./run R
 fi
